version: '3.5'
services:
  consul:
    image: consul
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
  customer_service:
    image: maksimstsiapanau/customer_service
    depends_on:
      - consul
    ports:
      - "7777:8081"
  customer_service2:
    image: maksimstsiapanau/customer_service
    depends_on:
      - consul
    ports:
      - "7778:8081"
  git2consul:
    image: cimpress/git2consul
    depends_on: 
      - consul
    volumes:
      - /tmp/git2consul.d:/etc/git2consul.d
    command: --endpoint consul --port 8500 --config-file /etc/git2consul.d/config.json
  application:
    image: appservice
    ports:
      - "8090:8082"
    depends_on:
      - consul
  application2:
    image: appservice
    ports:
      - "8091:8082"
    depends_on:
      - consul
  customer:
    image: customerservice
    ports:
      - "8092:8081"
    depends_on:
      - consul

  fabio:
    image: fabiolb/fabio:latest
    ports:
      - "9999:9999"
      - "9998:9998"
    depends_on:
      - consul
    volumes:
      - "/tmp/fabio.properties:/etc/fabio/fabio.properties"
