version: '3.5'
services:
  consul:
    image: consul
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
  router:
    image: maksimstsiapanau/nginx-consul:latest
    volumes:
      - "/tmp/customers.conf:/etc/consul-template/templates/customers.conf"
      - "/tmp/customers.hcl:/etc/consul-template/conf/customers.hcl"
    ports:
      - "9090:9090"
      - "8443:443"
  customer_service:
    image: maksimstsiapanau/customer_service
    depends_on:
      - consul
    ports:
      - "7777:8081"
  customer_service2:
    image: maksimstsiapanau/customer_service
    depends_on:
      - consul
    ports:
      - "7778:8081"
  git2consul:
    image: cimpress/git2consul
    depends_on: 
      - consul
    volumes:
      - /tmp/git2consul.d:/etc/git2consul.d
    command: --endpoint consul --port 8500 --config-file /etc/git2consul.d/config.json
  application:
    image: appservice
    container_name: app_service1
    ports:
      - "8090:8082"
    depends_on:
      - consul
  application2:
    image: appservice
    container_name: app_service2
    ports:
      - "8091:8082"
    depends_on:
      - consul

  fabio:
    image: fabiolb/fabio:latest
    ports:
      - "9999:9999"
      - "9998:9998"
    depends_on:
      - consul
    volumes:
      - "/tmp/fabio.properties:/etc/fabio/fabio.properties"
    environment:
      - SERVICE_9998_TAGS=urlprefix-/fabio
