version: '3.5'
services:
  consul:
    image: consul
    ports:
      - "8500:8500"
    volumes:
      - "./consul_config.json:/consul/config/config.json"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
  router:
    image: maksimstsiapanau/nginx-consul:latest
    depends_on:
      - consul
    volumes:
      - "./rkk_lb.conf:/etc/consul-template/templates/rkk_lb.conf"
      - "./rkk_lb.hcl:/etc/consul-template/conf/rkk_lb.hcl"
    ports:
      - "9090:9090"
      - "8443:443"
  customer_service:
    image: maksimstsiapanau/customer_service
    depends_on:
      - consul
      - git2consul
    ports:
      - "7777:8081"
  customer_service2:
    image: maksimstsiapanau/customer_service
    depends_on:
      - consul
      - git2consul
    ports:
      - "7778:8081"
  application:
    image: pbarbashov/appservice
    ports:
      - 8082
    depends_on:
      - consul
      - git2consul
  git2consul:
    image: cimpress/git2consul
    depends_on: 
      - consul
    volumes:
      - ./config.json:/etc/git2consul.d/config.json
    command: --endpoint consul --port 8500 --config-file /etc/git2consul.d/config.json
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"  
  vault:
    image: vault
    ports:
      - "8200:8200"
    depends_on:
      - consul
    environment:
      VAULT_ADDR: 'http://vault:8200'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault_config.json:/etc/vault/vault_config.json
    command: server -config /etc/vault/vault_config.json
 # fabio:
 #   image: fabiolb/fabio:latest
 #   ports:
 #     - "9999:9999"
 #     - "9998:9998"
 #   depends_on:
 #     - consul
 #   volumes:
 #     - "./fabio.properties:/etc/fabio/fabio.properties"
 #   environment:
 #     - SERVICE_9998_TAGS=urlprefix-/fabio
